import { Component, OnInit, signal, WritableSignal } from '@angular/core';
import { Config } from 'datatables.net';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import DataTable from 'datatables.net-dt';
// The 'datatables.net' package is a dependency of 'datatables.net-dt' and is included automatically.
// The Buttons and Select extensions also have '-dt' packages that include the default styling
// and are generally better suited for module bundlers like Vite.
import { DatePipe } from '@angular/common';
import { MatDialog, MatDialogRef } from '@angular/material/dialog';
import { TranslateService } from '@ngx-translate/core';
import 'datatables.net-buttons-dt';
import 'datatables.net-select-dt';
import { forkJoin, map, Observable, of } from 'rxjs';
import { AddEmployeeComponent } from "../add-employee/add-employee.component";
import { EmployeeService } from '../service/EmployeeService';
import { ConfirmationDialogComponent, ConfirmationDialogData } from '../shared/confirmation-dialog/confirmation-dialog.component';
import { ErrorDialogComponent, ErrorDialogData } from '../shared/error-dialog/error-dialog.component';
import { Employee } from '../shared/model/Employee';
import { SpinnerService } from '../service/spinner.service';
import { SpinnerComponent } from '../shared/spinner/spinner.component';

@Component({
  selector: 'app-data-tables2',
  templateUrl: './data-tables2.component.html',
  imports: [MatProgressSpinnerModule, SpinnerComponent],
  styleUrl: './data-tables2.component.scss'
})
export class DataTables2Component implements OnInit {

  private table!: any;
  public dtOptions: Config = {};
  private employeeIdToEmployeeMap: Map<string, Employee> = new Map();
  isLoading: WritableSignal<boolean> = signal(false);
  constructor(private dialog: MatDialog, 
    private employeeService: EmployeeService, private translate: TranslateService, private spinnerService: SpinnerService) { }

  ngOnInit(): void {
    this.spinnerService.show();
    // Using `get` ensures that the translations are loaded before we try to use them.
    // `instant` can fail if the component initializes before the translation file is fetched.
    this.translate.get([
      'new-employee', 'edit-employee', 'delete-employee', 'id', 'name', 'manager',
      'position', 'office', 'extn', 'start-date', 'salary', 'is-manager', 'actions',
      'yes', 'no'
    ]).subscribe(translations => {
      this.dtOptions = {
        layout: {
          top1Start: {
            buttons: [
              {
                text: translations['new-employee'],
                className: "btn btn-primary",
                action: () => {
                  const dialogRef: MatDialogRef<AddEmployeeComponent> =
                    this.dialog.open(AddEmployeeComponent,
                      {
                        disableClose: true,
                        data: null
                      });
                  dialogRef.afterClosed().subscribe(result => {
                    if (!result) {
                      return;
                    }
                    const e: Employee = new Employee(
                      "", // id is generated by backend
                      result.name,
                      result.position,
                      result.salary,
                      result.start_date,
                      result.office,
                      result.extn,
                      result.hasManagerRights,
                      result.manager
                    );
                    this.addEmployee(e);
                  })
                }
              }
            ]
          }
        },
        columnDefs: [{ "defaultContent": "", "targets": "_all" }],
        columns: [
          { data: 'id', title: translations['id'], visible: false },
          { data: 'name', title: translations['name'] },
          {
            data: 'manager',
            title: translations['manager'],
            defaultContent: "", // This prevents the error if 'manager' property is missing.
            render: (data, type, row) => {
              // For display and filtering, we want to show the manager's name.
              if (type === 'display' || type === 'filter') {
                // If `data` (which is `row.manager`) is null, there's no manager.
                if (data == null) {
                  return "";
                }

                // If `data` is a string, it's a manager's ID. Look it up in the map.
                if (typeof data === 'string') {
                  return this.employeeIdToEmployeeMap.get(data)?.name || '';
                }

                // If `data` is an object, it should have a `name` property.
                // This handles both Employee instances and plain objects from JSON.
                if (typeof data === 'object' && data.name) {
                  return data.name;
                }
              }

              // For sorting or other types, return the raw data.
              return data;
            }
          },
          { data: 'position', title: translations['position'] },
          { data: 'office', title: translations['office'] },
          { data: 'extn', title: translations['extn'] },
          {
            data: 'start_date', title: translations['start-date'], type: 'date', render: (data) => new DatePipe('cs-CZ').transform(data, 'dd.MM.yyyy') ?? ''
          },
          { data: 'salary', title: translations['salary'] },
          {
            data: 'hasManagerRights', title: translations['is-manager'], render: (data) => {
              // An employee is a manager *only* if `hasManagerRights` is true.
              // This corrects the logic that also considered top-level employees as managers.
              return data ? translations['yes'] : translations['no'];
            }
          },

          {
            title: translations['actions'],
            searchable: false,
            orderable: false,

            render: (data, type, row) => {
              return `<button name='editButton' style='width: 100%' class='btn btn-info btn-sm'>${translations['edit-employee']}</button><br/>` +
                `<button name='deleteButton' style='width: 100%;' class='btn btn-danger btn-sm mt-1'>${translations['delete-employee']}</button>`;
            }
          }]
        ,
        pageLength: 100,
        lengthMenu: [5, 10, 20, 50, 100],
        rowId: "id",
      };
      this.table = new DataTable($('#jsonTable'), this.dtOptions);

      // Use event delegation for action buttons for better performance.
      // This avoids re-binding events on every table draw.
      const tableBody = $('#jsonTable tbody');

      tableBody.on('click', "button[name='editButton']", (event) => {
        const rowElement = $(event.currentTarget).closest('tr');
        const id = rowElement.attr('id');
        if (!id) { return; }

        const row = this.table.row("#" + id);
        const rowData = row.data();

        if (!rowData) {
          return;
        }

        const dialogRef: MatDialogRef<AddEmployeeComponent> = this.dialog.open(AddEmployeeComponent, {
          disableClose: true,
          data: rowData
        });

        dialogRef.afterClosed().subscribe(result => {
          if (result) {
            this.editEmployee(result as Employee, row);
          }
        });
      });

      tableBody.on('click', "button[name='deleteButton']", (event) => {
        const rowElement = $(event.currentTarget).closest('tr');
        const id = rowElement.attr('id');
        if (!id) { return; }

        const dialogRef = this.dialog.open(ConfirmationDialogComponent, {
          data: {
            title: this.translate.instant('confirm-delete'),
            message: this.translate.instant('confirm-delete-message'),
            confirmText: this.translate.instant('delete'),
            cancelText: this.translate.instant('cancel')
          } as ConfirmationDialogData
        });

        dialogRef.afterClosed().subscribe((confirmed: boolean) => {
          if (confirmed) {
            this.deleteEmployee(id);
          }
        });
      });

      this.getEmployees();
    });

  }

  loadEmployeeWithManager(obj: any): Observable<Employee> | null {
    // Case 1: If the object itself is a string, treat it as an employee ID and load employee with manager
    if (typeof obj === 'string') {
      return this.employeeService.getEmployeeWithManager(obj); // Should load employee with manager
    }

    // Case 2: If manager is null, but managerId is a non-null string, load employee with that managerId
    if (obj && obj.manager == null && typeof obj.managerId === 'string' && obj.managerId) {
      return this.employeeService.getEmployeeWithManager(obj.managerId);
    }



    // Case 3: If manager is a string, treat it as an ID and load the employee as manager
    if (obj && typeof obj.manager === 'string' && obj.managerId) {
      return this.employeeService.getEmployeeWithManager(obj.managerId);
    }

    return null;
  }



  getEmployees(): void {
    this.isLoading.set(true);
    this.employeeIdToEmployeeMap.clear();
    this.table.clear();
    this.employeeService.getEmployeesWithManagers().subscribe({
      next: (res: any[]) => {
        if (!res || res.length === 0) {
          this.table.draw();
          this.isLoading.set(false);
          this.spinnerService.hide();
          return;
        }

        const employeeObservables = res.map(employeeData => {
          if (employeeData instanceof Employee) {
            return of(employeeData);
          }
          if (typeof employeeData === 'string') {
            return this.employeeService.getEmployeeWithManager(employeeData);
          }
          // This handles plain objects from JSON that are not Employee instances
          if (typeof employeeData === 'object' && employeeData !== null && 'id' in employeeData) {
            return of(employeeData as Employee);
          }

          console.warn('Unknown data type in getEmployees response and will be ignored:', employeeData);
          return of(null); // Return an observable of null for unknown types
        });

        forkJoin(employeeObservables).subscribe({
          next: (employees: (Employee | null)[]) => {
            console.log("SIZE=" + employees.length);
            const validEmployees = employees.filter((e): e is Employee => e !== null);

            validEmployees.forEach(employee => {
              this.employeeIdToEmployeeMap.set(employee.id, employee);
            });

            if (validEmployees.length > 0) {
              // Add data to the table's cache without drawing immediately.
              this.table.rows.add(validEmployees);
            }
            // Invalidate all rows to force re-running render functions (e.g., for manager names)
            // and then draw the table. This is the most reliable way to handle renderers with dependencies.
            this.table.rows().invalidate().draw();
            this.isLoading.set(false);
            this.spinnerService.hide();
          },
          error: (err: any) => {
            alert(this.translate.instant('failed-to-get-employees') + ': ' + err.message);
            this.isLoading.set(false);
            this.spinnerService.hide();
          }
        });

      },
      error: (err: any) => {
        alert(this.translate.instant('failed-to-get-employees') + ': ' + err.message);
        this.isLoading.set(false);
        this.spinnerService.hide();
      }
    });
  }

  addEmployee(emp: Employee): void {
    this.employeeService.createEmployee(emp).subscribe({
      next: (res: Employee) => {
        // Add the new employee to the manager map to ensure consistency
        this.employeeIdToEmployeeMap.set(res.id, res); // The draw() call will re-render the table with the new row.
        // A full getEmployees() call is not needed and is inefficient. Just add the new row and draw.
        this.table.row.add(res).draw();
      },
      error: (err: any) => {
        alert(this.translate.instant('failed-to-add-employee') + ': ' + err.message + " " + JSON.stringify(emp));
      }
    });
  }

  editEmployee(emp: Employee, rowToUpdate: any): void {
    this.employeeService.updateEmployee(emp).subscribe({
      next: (res: Employee) => {
        const oldData = rowToUpdate.data() || {};
        const newData = { ...oldData, ...res };

        this.employeeIdToEmployeeMap.set(newData.id, newData);

        rowToUpdate.data(newData);

        // Invalidate all rows to re-run render functions (e.g., for manager names)
        // and redraw the table without changing pagination. This is more efficient.
        this.table.rows().invalidate().draw(false);
      },
      error: (err: any) => {
        const dialogRef = this.dialog.open(ErrorDialogComponent, {
          data: {
            title: this.translate.instant('cycle-detected'),
            message: this.translate.instant('user-cannot-be-own-manager'),
            confirmText: this.translate.instant('ok'),

          } as ErrorDialogData
        });
      }
    });
  }

  deleteEmployee(id: string): void {
    this.employeeService.deleteEmployee(id).subscribe({
      next: () => {
        this.employeeIdToEmployeeMap.delete(id);
        this.table.row("#" + id).remove();
        // Invalidate all rows to re-run render functions (e.g., for manager names)
        // and redraw the table without changing pagination.
        this.table.rows().invalidate().draw(false);
      },
      error: (err: any) => {
        this.translate.get([
          'manager-cannot-be-deleted',
          'employee-cannot-be-deleted-has-subordinates' // Corrected typo from 'subordintes'
        ]).subscribe(translations => {
          this.dialog.open(ErrorDialogComponent, {
            data: {
              title: translations['manager-cannot-be-deleted'],
              message: translations['employee-cannot-be-deleted-has-subordinates'],
              confirmText: 'OK',
            } as ErrorDialogData
          });
        });
      }
    });
  }
}
