spring:
  application:
    name: listek-admin
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/listek}
    username: ${DB_USERNAME:listek}
    password: ${DB_PASSWORD:listek}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/admin
    table: flyway_schema_history_admin
    baseline-on-migrate: true
    baseline-version: 0

server:
  port: ${SERVER_PORT:8090}
