import { Component, OnInit, WritableSignal, signal } from '@angular/core';
import { MatDialog, MatDialogRef } from '@angular/material/dialog';
import { Config } from 'datatables.net';
import 'datatables.net-buttons-dt';
import 'datatables.net-select-dt';
import DataTable from 'datatables.net-dt';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { AddEmployeeComponent } from '../add-employee/add-employee.component';
import { EmployeeService } from '../service/EmployeeService';
import { Employee } from '../shared/model/Employee';
import { DatePipe } from '@angular/common';
import { ConfirmationDialogComponent, ConfirmationDialogData } from '../shared/confirmation-dialog/confirmation-dialog.component';
import { ErrorDialogComponent, ErrorDialogData } from '../shared/error-dialog/error-dialog.component';
import { TranslateModule, TranslateService } from '@ngx-translate/core';
import { TranslatePipe } from '@ngx-translate/core';
import { forkJoin, of } from 'rxjs';
import { SpinnerComponent } from '../shared/spinner/spinner.component';
import { SpinnerService } from '../service/spinner.service';

@Component({
  selector: 'app-data-tables3',
  templateUrl: './data-tables3.component.html',
  imports: [MatProgressSpinnerModule, SpinnerComponent],
  styleUrl: './data-tables3.component.scss'
})
export class DataTables3Component implements OnInit {

  private table!: any;
  private employeeIdToEmployeeMap: Map<string, Employee> = new Map();
  public dtOptions: Config = {};
  // Create a writable signal for the loading state, initialized to false.
  //  loading: WritableSignal<boolean> = signal(false);
  isLoading: WritableSignal<boolean> = signal(false);
  constructor(private dialog: MatDialog, private employeeService: EmployeeService,
    private translate: TranslateService, private spinnerService: SpinnerService) { }
  ngOnInit(): void {
    this.spinnerService.show();
    // Using `get` ensures that the translations are loaded before we try to use them.
    // `instant` can fail if the component initializes before the translation file is fetched.
    this.translate.get([
      'datatables.info', 'new-employee', 'edit-employee', 'remove-employee', 'confirm-delete',
      'confirm-delete-message', 'delete', 'cancel', 'id', 'name', 'manager', 'position',
      'office', 'extn', 'start-date', 'salary', 'is-manager', 'yes', 'no'
    ]).subscribe(translations => {
      this.dtOptions = {
        language: {
          info: translations['datatables.info']
        },
        layout: {
          bottom2Start: {
            buttons: [
              {
                text: translations['new-employee'],
                className: "btn btn-primary",
                action: () => {
                  const dialogRef: MatDialogRef<AddEmployeeComponent> = this.dialog.open(AddEmployeeComponent,
                    {
                      disableClose: true,
                      data: null
                    });
                  dialogRef.afterClosed().subscribe(result => {
                    if (!result) {
                      return;
                    }
                    const e: Employee = new Employee(
                      "", // id is generated by backend
                      result.name,
                      result.position,
                      result.salary,
                      result.start_date,
                      result.office,
                      result.extn,
                      result.hasManagerRights,
                      result.manager);
                    this.addEmployee(e);
                  });
                }

              },
              {
                text: translations['edit-employee'],
                className: "my-button my-disabled-button btn btn-primary",
                name: "editButton",
                action: () => {
                  const rowData = this.table.row(".selected").data();
                  if (rowData == null || rowData == undefined) {
                    return;
                  }
                  const dialogRef: MatDialogRef<AddEmployeeComponent> =
                    this.dialog.open(AddEmployeeComponent,
                      {
                        disableClose: true,
                        data: rowData
                      }
                    )

                  dialogRef.afterClosed().subscribe(result => {
                    if (!result) {
                      return;
                    }
                    const e: Employee = new Employee(
                      result.id,
                      result.name,
                      result.position,
                      result.salary,
                      result.start_date,
                      result.office,
                      result.extn,
                      result.hasManagerRights,
                      result.manager);
                    this.editEmployee(e);
                  });

                }
              },
              {
                text: translations['remove-employee'],
                className: "my-button my-disabled-button btn btn-primary",
                name: "deleteButton",
                action: () => {
                  const rowId = this.table.row('.selected').id();
                  if (rowId != undefined && rowId != null) {
                    const dialogRef = this.dialog.open(ConfirmationDialogComponent, {
                      data: {
                        title: translations['confirm-delete'],
                        message: translations['confirm-delete-message'],
                        confirmText: translations['delete'],
                        cancelText: translations['cancel']
                      } as ConfirmationDialogData
                    });
                    dialogRef.afterClosed().subscribe((confirmed: boolean) => {
                      if (confirmed) {
                        this.deleteEmployee(rowId);
                      }
                    });
                  }
                }
              }
            ]
          }
        },
        columns: [
          { data: 'id', title: translations['id'], visible: false },
          { data: 'name', title: translations['name'] },
          {
            data: 'manager',
            title: translations['manager'],
            defaultContent: "", // This prevents the error if 'manager' property is missing.
            render: (data, type, row) => {
              // For display and filtering, we want to show the manager's name.
              if (type === 'display' || type === 'filter') {
                // If `data` (which is `row.manager`) is null, there's no manager.
                if (data == null) {
                  return "";
                }

                // If `data` is a string, it's a manager's ID. Look it up in the map.
                if (typeof data === 'string') {
                  return this.employeeIdToEmployeeMap.get(data)?.name || '';
                }

                // If `data` is an object, it should have a `name` property.
                // This handles both Employee instances and plain objects from JSON.
                if (typeof data === 'object' && data.name) {
                  return data.name;
                }
              }

              // For sorting or other types, return the raw data.
              return data;
            }
          },
          { data: 'position', title: translations['position'] },
          { data: 'office', title: translations['office'] },
          { data: 'extn', title: translations['extn'] },
          { data: 'start_date', title: translations['start-date'], render: (data: any) => new DatePipe('cs-CZ').transform(data, 'dd.MM.yyyy') ?? '' },
          { data: 'salary', title: translations['salary'] },
          {
            data: 'hasManagerRights', title: translations['is-manager'], render: (data) => {
              // An employee is a manager *only* if `hasManagerRights` is true.
              // This corrects the logic that also considered top-level employees as managers.
              return data ? translations['yes'] : translations['no'];
            }
          },
        ],
        pageLength: 100, // The rest of your config is fine
        lengthMenu: [5, 10, 20, 50, 100], // ...
        lengthChange: true, // ...
        info: true, // ...
        infoCallback(settings, start, end, max, total, pre) { // ...
          return 'From ' + start + ' to ' + end + " of " + max + ' rows<br/>'; // ...
        }, // ...
        select: { // ...
          style: 'single', // ...
          info: false, // ...
        }, // ...
        rowId: "id" // ...
      };
      this.table = new DataTable($('#jsonTable3'), this.dtOptions);
      this.getEmployees();

      // Event handlers are fine
      this.table.on('page', () => { this.table.rows().deselect(); });
      this.table.on('order', () => { this.table.rows().deselect(); });
      this.table.on('search', () => { this.table.rows().deselect(); });
      this.table.on('select', () => $('.my-button').removeClass("my-disabled-button"))
        .on('deselect', () => $('.my-button').addClass("my-disabled-button"));
    });
    
  };


  addEmployee(emp: Employee): void {



    this.employeeService.createEmployee(emp).subscribe({
      next: (res: Employee) => {
        this.employeeIdToEmployeeMap.set(res.id, res);
        this.table.row.add(res).draw();
      },
      error: (err: any) => {
        alert(this.translate.instant('failed-to-add-employee') + ': ' + err.message);
      }
    });
  }

  editEmployee(emp: Employee): void {
    this.employeeService.updateEmployee(emp).subscribe({
      next: (res: Employee) => {
        const rowToUpdate = this.table.row('.selected');
        const oldData = rowToUpdate.data() || {}; // Safely get old data
        const newData = { ...oldData, ...res };

        // Update the map to prevent stale manager data for other rows
        this.employeeIdToEmployeeMap.set(newData.id, newData);

        rowToUpdate.data(newData);

        // Invalidate all rows to re-run render functions (e.g., for manager names) and redraw.
        this.table.rows().invalidate().draw(false);
      },
      error: (err: any) => {
        const dialogRef = this.dialog.open(ErrorDialogComponent, {
          data: {
            title: this.translate.instant('cycle-detected'),
            message: this.translate.instant('user-cannot-be-own-manager'),
            confirmText: this.translate.instant('ok'),

          } as ErrorDialogData
        });
      }
    });
  }


  deleteEmployee(empId: string) {
    this.employeeService.deleteEmployee(empId).subscribe({
      next: () => {
        this.employeeIdToEmployeeMap.delete(empId);
        this.table.row(".selected").remove();
        // Invalidate all rows to re-run render functions (e.g., for manager names)
        // and redraw the table without changing pagination.
        this.table.rows().invalidate().draw(false);
      },
      error: (err: any) => {
        this.translate.get(['manager-cannot-be-deleted', 'employee-cannot-be-deleted-has-subordinates'])
          .subscribe(translations => {
            this.dialog.open(ErrorDialogComponent, {
              data: {
                title: translations['manager-cannot-be-deleted'],
                message: translations['employee-cannot-be-deleted-has-subordinates'],
                confirmText: 'OK',
              } as ErrorDialogData
            });
          });
      }
    });
  }

  getEmployees(): void {
    this.isLoading.set(true);
    this.employeeIdToEmployeeMap.clear();
    this.table.clear();
    this.employeeService.getEmployeesWithManagers().subscribe({
      next: (res: any[]) => {
        if (!res || res.length === 0) {
          this.table.draw();
          this.isLoading.set(false);
          this.spinnerService.hide();
          return;
        }

        const employeeObservables = res.map(employeeData => {
          if (employeeData instanceof Employee) {
            return of(employeeData);
          }
          if (typeof employeeData === 'string') {
            return this.employeeService.getEmployeeWithManager(employeeData);
          }
          // This handles plain objects from JSON that are not Employee instances
          if (typeof employeeData === 'object' && employeeData !== null && 'id' in employeeData) {
            return of(employeeData as Employee);
          }

          console.warn('Unknown data type in getEmployees response and will be ignored:', employeeData);
          return of(null); // Return an observable of null for unknown types
        });

        forkJoin(employeeObservables).subscribe({
          next: (employees: (Employee | null)[]) => {
            const validEmployees = employees.filter((e): e is Employee => e !== null);

            validEmployees.forEach(employee => {
              this.employeeIdToEmployeeMap.set(employee.id, employee);
            });

            if (validEmployees.length > 0) {
              // Add data to the table's cache without drawing immediately.
              this.table.rows.add(validEmployees);
            }
            // Invalidate all rows to force re-running render functions (e.g., for manager names)
            // and then draw the table. This is the most reliable way to handle renderers with dependencies.
            this.table.rows().invalidate().draw();
            this.isLoading.set(false);
            this.spinnerService.hide();
          },
          error: (err: any) => {
            alert(this.translate.instant('failed-to-get-employees') + ': ' + err.message);
            this.isLoading.set(false);
            this.spinnerService.hide();
          }
        });

      },
      error: (err: any) => {
        alert(this.translate.instant('failed-to-get-employees') + ': ' + err.message);
        this.isLoading.set(false);
        this.spinnerService.hide();
      }
    });
  }

}
